server:
  port: 8094

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5434/currency
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: currency
        show_sql: ${SHOW_SQL:false}
        format_sql: ${FORMAT_SQL:true}
        highlight_sql: ${HIGHLIGHT_SQL:true}
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: ${SLOW_SQL_QUERY_INDICATOR_MS:1500}
        hbm2ddl:
          auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

client:
  frankfurter:
    url: https://api.frankfurter.dev/v1
    correctionFactor: 1


otel:
  exporter:
    otlp:
      endpoint:
        ${OTLP_EXPORTER_ENDPOINT:http://localhost:4318}
      protocol: http/protobuf
  logs:
    exporter: none
  metrics:
    exporter: none

logging:
  config: "classpath:logback-local.xml"
  level.net.javacrumbs.shedlock: DEBUG
  level.net.javacrumbs.shedlock.provider.jdbctemplate: DEBUG

