global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'individuals-api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'individuals-api:8091' ]

  - job_name: 'persons-api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'persons-api:8092' ]

  - job_name: 'transactions-api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'transactions-api:8093' ]

  - job_name: 'currencies-api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'currencies-api:8094' ]