{
 "title": "HTTP Endpoints Metrics",
 "description": "HTTP endpoints metrics",
 "tags": [
  "http",
  "endpoints",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Requests Count per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by (uri, method) (http_server_requests_seconds_count{error=\"none\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Average Request Duration per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (uri, method) (http_server_requests_seconds_sum{error=\"none\"}) / sum by (uri, method) (http_server_requests_seconds_count{error=\"none\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Application Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by (uri, method, error, outcome) (http_server_requests_seconds_count{outcome != \"SUCCESS\"} or http_server_requests_seconds_count{error != \"none\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}