application:
  keycloak:
    serverUrl: http://localhost:9090
    tokenUrl: ${application.keycloak.serverUrl}/realms/${application.keycloak.realm}/protocol/openid-connect/token
    realm: individual
    clientId: individual
    clientSecret: FaxzBgk7pkyattBrV8MlVCVg80jjZKo5
    adminUsername: admin
    adminPassword: admin
    adminClientId: admin-cli

spring:
  application:
    name: individual-api
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${application.keycloak.clientId}
            client-secret: ${application.keycloak.clientSecret}
            client-name: individual
            authorization-grant-type: authorization_code
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: ${application.keycloak.serverUrl}/realms/${application.keycloak.realm}

server:
  port: 8091
