server:
  port: 8091

application:
  keycloak:
    serverUrl: ${KEYCLOAK_URL:http://localhost:8080}
    realmUrl: ${application.keycloak.serverUrl}/realms/${application.keycloak.realm}
    tokenUrl: ${application.keycloak.realmUrl}/protocol/openid-connect/token
    realm: individual
    clientId: individual
    clientSecret: FaxzBgk7pkyattBrV8MlVCVg80jjZKo5
    adminEmail: admin@gmail.com
    adminPassword: admin
    adminClientId: admin-cli

spring:
  application:
    name: individual-api
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${application.keycloak.clientId}
            client-secret: ${application.keycloak.clientSecret}
            client-name: individual
            authorization-grant-type: authorization_code
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: ${application.keycloak.serverUrl}/realms/${application.keycloak.realm}

person:
  name: person
  url: ${PERSONS_API_URL:http://localhost:8092}

transaction:
  name: transaction
  url: ${TRANSACTIONS_API_URL:http://localhost:8093}

wallet:
  name: wallet
  url: ${TRANSACTIONS_API_URL:http://localhost:8093}

currency:
  name: currency
  url: ${CURRENCY_API_URL:http://localhost:8094}

logging:
  config: "classpath:logback.xml"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint:
        ${OTLP_EXPORTER_ENDPOINT:http://localhost:4318}
      protocol: http/protobuf
  logs:
    exporter: none
  metrics:
    exporter: none

